---
title: "Stats 141XP - Final Project 3"
author: 'Anna Lee'
date: "2/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r finalproj}
##### glm with non-mucor patients, i.e., with weights
joinw <- read.csv('Joined2_FULL.csv')

# getting rid of rows with weird values for mortality
trash <- c()
for (i in 1:nrow(joinw)) {
  if (joinw[i, ]$DIED != 0 && joinw[i, ]$DIED != 1) {
    trash <- c(trash, i)
  }
}
joinw <- joinw[-trash, ]

# assigning weights per observation
joinw$wt <- c(rep(1, 68), rep((66018-68)/6800, 66018-68))

# the model
m1 <- glm(DIED ~ AGE + DISPUNIFORM + FEMALE + I10_NPR + RACE + HOSP_LOCTEACH + HOSP_REGION + COMOR,
          family = binomial, data = joinw, weights = wt)
summary(m1)


##### glm with just mucor patients, i.e., no weights
join <- read.csv('Joined2.csv')
m2 <- glm(DIED ~ AGE + DISPUNIFORM + FEMALE + I10_NPR + RACE + HOSP_LOCTEACH + HOSP_REGION + COMOR,
          family = binomial, data = join)
summary(m2)

# penalized logistic regression
library(logistf)
logistf::logistf(formula = DIED ~ AGE + DISPUNIFORM + FEMALE + I10_NPR + RACE +
                   HOSP_LOCTEACH + HOSP_REGION + COMOR, data = join)
```

```{r edastuff}
hist(join$COMOR)
boxplot(join$COMOR ~ join$DIED)

table(join$RACE, join$DIED)
table(join$HOSP_REGION, join$DIED)

hist(join$AGE)

boxplot(join$COMOR ~ join$HOSP_REGION)

par(mfrow=c(1,2))
boxplot(join$COMOR ~ join$DIED, xlab="Mortality", ylab="Comorbidity Score")
boxplot(join$COMOR ~ join$HOSP_REGION, xlab="Hospital Region", ylab="Comorbidity Score")

###########



join6 <- read.csv('Joined6.csv')
allicds <- as.factor(substr(as.vector(as.matrix(join6[, 17:56])), 1, 3))
barplot(prop.table(table(allicds)))


common <- tail(head(sort(table(allicds), decreasing=TRUE), 35), 34)
common
barplot(prop.table(common), las = 2, cex.names = 0.7)
```
